## hosts/msi-ge75-raider-nixos/hardware-configuration.nix
# Generated by nixos-generate-config. Do not modify; edit configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Bootloader configured in hosts/msi-ge75-raider-nixos/configuration.nix (systemd-boot)

  # Temporary placeholder for root filesystem (replace UUID and device after install)
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000"; # Placeholder UUID - replace with real from blkid
      fsType = "ext4";
    };

  # Temporary placeholder for swap (optional; comment out if no swap, or replace after install)
  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000"; }  # Placeholder - replace or remove
  #   ];

  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
