name: Flake Check (Manual)

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Nix fmt (check)
        run: nix fmt -- --check .
      - name: Statix check
        run: nix run nixpkgs#statix -- check
      - name: Flake check
        run: nix flake check
