name: Nix Flake Check
on:
  push:
  pull_request:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Check flake
        run: nix flake check -L

